CREATE PROC FI_SP_IncCliente
    @NOME          VARCHAR (50) ,
    @SOBRENOME     VARCHAR (255),
    @CPF           VARCHAR (14) ,
    @NACIONALIDADE VARCHAR (50) ,
    @CEP           VARCHAR (9)  ,
    @ESTADO        VARCHAR (2)  ,
    @CIDADE        VARCHAR (50) ,
    @LOGRADOURO    VARCHAR (500),
    @EMAIL         VARCHAR (2079),
    @TELEFONE      VARCHAR (15) ,
    @BENEFICIARIOS BeneficiariosList NULL READONLY
AS
BEGIN TRAN ADD_CLIENT_TRAN
	INSERT INTO CLIENTES (NOME, SOBRENOME, CPF, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE) 
	VALUES (@NOME, @SOBRENOME,@CPF,@NACIONALIDADE,@CEP,@ESTADO,@CIDADE,@LOGRADOURO,@EMAIL,@TELEFONE)

	DECLARE @NovoId BIGINT = SCOPE_IDENTITY();

    IF ((SELECT COUNT(1) FROM @BENEFICIARIOS) > 0 AND @NovoId > 0)
        DECLARE @CpfBen VARCHAR (14) = ''
        DECLARE @NomeBen VARCHAR (50) = ''

        DECLARE db_cursor CURSOR FOR SELECT CPF, NOME FROM @BENEFICIARIOS

        OPEN db_cursor  
        FETCH NEXT FROM db_cursor INTO @CpfBen, @NomeBen

        WHILE @@FETCH_STATUS = 0  
        BEGIN  
            EXEC dbo.FI_SP_IncBeneficiario @NOME = @NomeBen, @CPF = @CpfBen, @IDCLIENTE = @NovoId;

            FETCH NEXT FROM db_cursor INTO @CpfBen, @NomeBen
        END

    SELECT @NovoId;
COMMIT TRAN ADD_CLIENT_TRAN