CREATE PROC FI_SP_VerificaCliente
	@CPF VARCHAR (14)
AS
BEGIN
	IF(ISNULL(@CPF,'') = '')
		SELECT 0 AS Existente
	ELSE
		SELECT IIF(COUNT(ID) > 0, 1, 0) AS Existente
		FROM CLIENTES
		WITH(NOLOCK)
		WHERE CPF = @CPF
END